### ISSUE TITLE
Adding Dynamic data source 

### ISSUE THREAD

**Issue by n3m3sis00** [n3m3sis00/tree#5]
Currently, program uses data stored internally in component to render tree.

### Requirements
- [x] Manually paste data in textbox
- [x] Get files from server endpoint hosting various files altogether 
   - [x]  for example **_python http.server_**
   - [x]  for example _**node live-server**_
- [x] Upload data.txt file for real-time rendering
- [ ] Listen to Jbrowse endpoint for data

**Comment by n3m3sis00** [comment]
### Feature

* Bottom Drawer
* Tabbed View
* Iconify

### Fixes
* Paste Bin Material-UI
* TreeData From store*

### Screenshot

![img](https://user-images.githubusercontent.com/34513489/85164511-18d00500-b282-11ea-954d-5b97d945cb3a.png)

**Comment by n3m3sis00** [comment]
### Feature
- TXT parser
- connect to file server
- onClick render tree using data from file 

### TODO
- Material-UI Styling
- remove Extra _files.txt_ file dependency
- CORS ISSUE

### Screenshot

![img](https://user-images.githubusercontent.com/34513489/85219275-078d1280-b3c0-11ea-8400-bcd5391cfc6b.png)

**Comment by n3m3sis00** [comment]
### Feature
- TXT parser
- upload multiple file
- onClick render tree using data from file 

### TODO
- Material-UI Styling
- drap and drop
- CORS ISSUE

### Screenshot

![img](https://user-images.githubusercontent.com/34513489/85225838-80589280-b3f1-11ea-8bbd-a5b64952efab.png)

**Comment by cmdcolin** [comment]
This looks pretty good now! I'll close for now, we'll think about the jbrowse endpoint integration sometime soon
